sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

services:
    - redis-server

before_script:
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit
